package snax.simd

import chisel3._

import play.api.libs.json._

/** Generator for the standalone SIMD block.
  *
  * Deliberately parallel to `snax.xdma.xdmaTop.XDMATopGen`: same `--...Cfg` JSON handoff from snaxgen, same
  * CIRCT blackbox-resource hoisting, same `--sw-only` fast path for software-only rebuilds. Parameter
  * construction lives in `SimdCfgParser` so the combined-elaboration path in `XDMATopGen` can reuse it.
  *
  * NOTE ON `--sw-only`: when a cluster carries BOTH an xDMA and a SIMD block, the RTL for both is emitted by
  * `XDMATopGen --simdCfg` in a single Chisel elaboration, and this generator is invoked with `--sw-only` for the
  * header alone. Two separate elaborations would emit two differently-optimised copies of the modules they
  * share (`BasicCounter`, the `Fp*` units, the width converters), which is a hard compile error the moment both
  * files are in one design -- see the plan's §P1.5.
  *
  * Expected `snax_simd_cfg` shape:
  * {{{
  * snax_simd_cfg: {
  *   bender_target: [ snax_..._cluster_simd ]
  *   cfg_io_width: 32
  *   num_channel: 8                      // beat = num_channel * cluster.data_width bits
  *   reader_buffer: 12
  *   writer_buffer: 12
  *   reader_agu_temporal_dimension: 5
  *   writer_agu_temporal_dimension: 5
  *   reader_extensions: { HasStreamMap: {...}, HasStreamReduce: {...}, ... }
  * }
  * }}}
  */
object SimdTopGen extends App {
  val parsedArgs = snax.utils.ArgParser.parse(args)

  val simdCfg = parsedArgs.find(_._1 == "simdCfg")
  if (simdCfg.isEmpty) {
    println("simdCfg is not provided, generation failed. ")
    sys.exit(-1)
  }
  val parsedSimdCfg: JsValue = Json.parse(simdCfg.get._2)

  val clusterName   = parsedArgs.getOrElse("clusterName", "unnamed_cluster")
  val tcdmDataWidth = parsedArgs("tcdmDataWidth").toInt
  val axiDataWidth  = parsedArgs("axiDataWidth").toInt
  val tcdmSize      = parsedArgs("tcdmSize").toInt

  val numChannel = SimdCfgParser.numChannel(parsedSimdCfg, tcdmDataWidth, axiDataWidth)
  val param      = SimdCfgParser(parsedSimdCfg, tcdmDataWidth, axiDataWidth, tcdmSize)

  val readerParam    = param.readerParam
  val writerParam    = param.writerParam
  val extensionParam = param.extParam

  // ---------------------------------------------------------------- RTL
  val swOnly = parsedArgs.contains("sw-only")

  if (!swOnly) {
    var svString = getVerilogString(new SimdTop(param = param, clusterName = clusterName))

    // Chisel appends its blackbox file list at the end of the emitted file; drop it.
    val truncated = svString
      .split("\n")
      .takeWhile(
        !_.contains("""// ----- 8< ----- FILE "firrtl_black_box_resource_files.f" ----- 8< -----""")
      )

    // CIRCT inlines blackbox resource files (fpnew_pkg_snax and friends, pulled in by the FP extensions) AFTER
    // the circuit that instantiates them. SystemVerilog packages must be declared before use, so hoist the
    // inlined resource block ahead of the main circuit. Same fix as XDMATop.scala:380-395.
    val firstResIdx = truncated.indexWhere(_.contains("// ----- 8< ----- FILE"))
    svString =
      if (firstResIdx >= 0) (truncated.drop(firstResIdx) ++ truncated.take(firstResIdx)).mkString("\n")
      else truncated.mkString("\n")

    val hardwareDir =
      parsedArgs.getOrElse("hw-target-dir", "generated") + "/" + s"${clusterName}_simd.sv"
    java.nio.file.Files.write(
      java.nio.file.Paths.get(hardwareDir),
      svString.getBytes(java.nio.charset.StandardCharsets.UTF_8)
    )
  }

  // ---------------------------------------------------------------- SW header
  // Laid out in the SAME ORDER as snax-xdma-addr.h (reader, extensions, writer, start, then the read-only bank)
  // so the snax-simd-lib port from snax-xdma-lib stays mechanical.
  val macroDir = parsedArgs.getOrElse("sw-target-dir", "generated/include/snax-simd-addr.h")

  val readerTempDim = readerParam.aguParam.temporalDimension
  val writerTempDim = writerParam.aguParam.temporalDimension

  var macroTemplate =
    s"""// Copyright 2026 KU Leuven.
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0

// This file is automatically generated by the SIMD hardware generator corresponding to the hardware
// configuration. Do not modify or commit this file to the repository manually.

#define SIMD_WIDTH ${numChannel * tcdmDataWidth / 8}
#define SIMD_SPATIAL_CHAN ${numChannel}

// Reader region
#define SIMD_SRC_ADDR_PTR_LSB 0
#define SIMD_SRC_ADDR_PTR_MSB SIMD_SRC_ADDR_PTR_LSB + 1
#define SIMD_SRC_SPATIAL_STRIDE_PTR SIMD_SRC_ADDR_PTR_MSB + 1
#define SIMD_SRC_TEMP_DIM ${readerTempDim}
#define SIMD_SRC_TEMP_BOUND_PTR SIMD_SRC_SPATIAL_STRIDE_PTR + 1
#define SIMD_SRC_TEMP_STRIDE_PTR SIMD_SRC_TEMP_BOUND_PTR + SIMD_SRC_TEMP_DIM
#define SIMD_SRC_ENABLED_CHAN_PTR SIMD_SRC_TEMP_STRIDE_PTR + SIMD_SRC_TEMP_DIM

// Extension region
#define SIMD_EXT_NUM ${extensionParam.length}
#define SIMD_EXT_ENABLE_PTR SIMD_SRC_ENABLED_CHAN_PTR + 1
#define SIMD_EXT_CSR_PTR SIMD_EXT_ENABLE_PTR + ${if (extensionParam.nonEmpty) 1 else 0}
#define SIMD_EXT_CSR_NUM ${param.extUserCsrNum}
#define SIMD_EXT_CUSTOM_CSR_NUM \\
    { ${extensionParam.map(_.extensionParam.userCsrNum).mkString(", ")} }

// Writer region
#define SIMD_DST_ADDR_PTR_LSB SIMD_EXT_CSR_PTR + SIMD_EXT_CSR_NUM
#define SIMD_DST_ADDR_PTR_MSB SIMD_DST_ADDR_PTR_LSB + 1
#define SIMD_DST_SPATIAL_STRIDE_PTR SIMD_DST_ADDR_PTR_MSB + 1
#define SIMD_DST_TEMP_DIM ${writerTempDim}
#define SIMD_DST_TEMP_BOUND_PTR SIMD_DST_SPATIAL_STRIDE_PTR + 1
#define SIMD_DST_TEMP_STRIDE_PTR SIMD_DST_TEMP_BOUND_PTR + SIMD_DST_TEMP_DIM
#define SIMD_DST_ENABLED_CHAN_PTR SIMD_DST_TEMP_STRIDE_PTR + SIMD_DST_TEMP_DIM
#define SIMD_DST_ENABLED_BYTE_PTR SIMD_DST_ENABLED_CHAN_PTR + 1

// Launch. Must be the LAST read-write CSR: the ReqRspManager derives its launch pulse from a write here.
#define SIMD_START_PTR SIMD_DST_ENABLED_BYTE_PTR + 1

// Read-only bank, immediately after the read-write bank.
#define SIMD_SUBMITTED_TASK_PTR SIMD_START_PTR + 1
#define SIMD_FINISHED_TASK_PTR SIMD_SUBMITTED_TASK_PTR + 1
#define SIMD_PERF_CTR_TASK SIMD_FINISHED_TASK_PTR + 1
#define SIMD_PERF_CTR_READER SIMD_PERF_CTR_TASK + 1
#define SIMD_PERF_CTR_WRITER SIMD_PERF_CTR_READER + 1
// [0] busy, [1] a task never started (sticky, bad config), [2] task queue full
#define SIMD_STATUS SIMD_PERF_CTR_WRITER + 1

// Total read-write CSRs, for a compile-time cross-check against SIMD_START_PTR + 1.
#define SIMD_RW_CSR_NUM ${param.totalRwCsrNum}
"""

  macroTemplate = macroTemplate + """
// Operator ids, and the CONSTANT CSR base of each one.
//
// The base matters as much as the id: csrw_ss is a switch over the CSR number
// (RISC-V csrw takes an immediate), so a write whose address the compiler can
// fold costs one instruction while a computed one costs a jump-table load from
// L2 plus an indirect jump. Emitting the per-operator base here lets software
// write operator CSRs at compile-time-constant addresses instead of walking
// SIMD_EXT_CUSTOM_CSR_NUM at run time.
"""
  var csrCursor = 0
  for ((ext, i) <- extensionParam.zipWithIndex) {
    val name = ext.extensionParam.moduleName.toUpperCase
    macroTemplate = macroTemplate +
      s"""#define SIMD_EXT_${name} ${i}
#define SIMD_EXT_${name}_CSR (SIMD_EXT_CSR_PTR + ${csrCursor})
#define SIMD_EXT_${name}_CSR_NUM ${ext.extensionParam.userCsrNum}
"""
    csrCursor += ext.extensionParam.userCsrNum
  }

  val macroPath   = java.nio.file.Paths.get(macroDir)
  val macroParent = macroPath.getParent
  if (macroParent != null && !java.nio.file.Files.exists(macroParent)) {
    java.nio.file.Files.createDirectories(macroParent)
  }
  java.nio.file.Files.write(
    macroPath,
    macroTemplate.getBytes(java.nio.charset.StandardCharsets.UTF_8)
  )
}
