// Copyright 2025 KU Leuven.
// Solderpad Hardware License, Version 0.51, see LICENSE for details.
// SPDX-License-Identifier: SHL-0.51
//
// Xiaoling Yi <xiaoling.yi@esat.kuleuven.be>
// This file is generated by VersaCore module in hw/chisel_acc to wrap the generated verilog code automatically, do not modify it manually
// Generated at 2025-09-22T13:29:41.509215103Z

//-------------------------------
// Accelerator wrapper
//-------------------------------

module snax_versacore_shell_wrapper #(
    // Custom parameters. As much as possible,
    // these parameters should not be taken from outside
    parameter int unsigned RegRWCount   = 7,
    parameter int unsigned RegROCount   = 2,
    parameter int unsigned DataWidthA   = 1024,
    parameter int unsigned DataWidthB   = 512,
    parameter int unsigned DataWidthC   = 4096,
    parameter int unsigned DataWidthD = 4096,
    parameter int unsigned RegDataWidth = 32,
    parameter int unsigned RegAddrWidth = 32
) (
    //-------------------------------
    // Clocks and reset
    //-------------------------------
    input logic clk_i,
    input logic rst_ni,

    //-------------------------------
    // Accelerator ports
    //-------------------------------
    // Note, we maintained the form of these signals
    // just to comply with the top-level wrapper

    // Ports from accelerator to streamer
    output logic [DataWidthD-1:0] acc2stream_0_data_o,
    output logic acc2stream_0_valid_o,
    input logic acc2stream_0_ready_i,

    // Ports from streamer to accelerator
    input logic [DataWidthA-1:0] stream2acc_0_data_i,
    input logic stream2acc_0_valid_i,
    output logic stream2acc_0_ready_o,

    input logic [DataWidthB-1:0] stream2acc_1_data_i,
    input logic stream2acc_1_valid_i,
    output logic stream2acc_1_ready_o,

    input logic [DataWidthC-1:0] stream2acc_2_data_i,
    input logic stream2acc_2_valid_i,
    output logic stream2acc_2_ready_o,

    //-------------------------------
    // CSR manager ports
    //-------------------------------
    input  logic [RegRWCount-1:0][RegDataWidth-1:0] csr_reg_set_i,
    input  logic                                    csr_reg_set_valid_i,
    output logic                                    csr_reg_set_ready_o,
    output logic [RegROCount-1:0][RegDataWidth-1:0] csr_reg_ro_set_o
);
  assign csr_reg_ro_set_o[0][31:1] = 0;

  VersaCore inst_VersaCore (
      .clock(clk_i),
      .reset(~rst_ni),

      .io_data_in_a_ready(stream2acc_0_ready_o),
      .io_data_in_a_valid(stream2acc_0_valid_i),
      .io_data_in_a_bits (stream2acc_0_data_i),

      .io_data_in_b_ready(stream2acc_1_ready_o),
      .io_data_in_b_valid(stream2acc_1_valid_i),
      .io_data_in_b_bits (stream2acc_1_data_i),

      .io_data_in_c_ready(stream2acc_2_ready_o),
      .io_data_in_c_valid(stream2acc_2_valid_i),
      .io_data_in_c_bits (stream2acc_2_data_i),

      .io_data_out_d_ready(acc2stream_0_ready_i),
      .io_data_out_d_valid(acc2stream_0_valid_o),
      .io_data_out_d_bits (acc2stream_0_data_o),

      .io_ctrl_ready(csr_reg_set_ready_o),
      .io_ctrl_valid(csr_reg_set_valid_i),
      .io_ctrl_bits_fsmCfg_K_i(csr_reg_set_i[0]),
      .io_ctrl_bits_fsmCfg_N_i(csr_reg_set_i[1]),
      .io_ctrl_bits_fsmCfg_M_i(csr_reg_set_i[2]),
      .io_ctrl_bits_fsmCfg_subtraction_constant_i(csr_reg_set_i[3]),
      .io_ctrl_bits_arrayCfg_arrayShapeCfg(csr_reg_set_i[4]),
      .io_ctrl_bits_arrayCfg_dataTypeCfg(csr_reg_set_i[5]),

      .io_busy_o(csr_reg_ro_set_o[0][0]),
      .io_performance_counter(csr_reg_ro_set_o[1])

  );

endmodule
