# Copyright 2024 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

context:
  git_repo_url: "https://github.com/kuleuven-micas/snax_cluster"
  latest_tag: ${{ git.latest_tag( git_repo_url ) }}
  version: ${{ latest_tag[1:] }}

package:
  name: snax-cluster
  version: ${{ version }}

source:
  git: https://github.com/KULeuven-MICAS/snax_cluster
  tag: v${{ version }}

about:
  homepage: https://github.com/KULeuven-MICAS/snax_cluster
  summary: "A heterogeneous accelerator-centric compute cluster"

requirements:
  build:
    - python >= 3.12.0, < 3.13.0
    - pip
    - bender
    - git
    - wget
    - verilator >=5.30,<6
    - make >=4.4.1,<5
    - clang >=19.1.6,< 20
    - clangxx >=19.1.6,<20
    - clang-format >=19.1.6,<20
    - lld >=19.1.7,<20
    - llvm-tools >=19.1.7,<20
    - pandas >=2.2.3,<3
    - jsonref >=1.1.0,<2
    - jsonschema >=4.23.0,<5
    - mako >=1.3.8,<2
    - pyyaml >=6.0.2,<7
    - termcolor >=2.5.0,<3
    - pyelftools >=0.31,<0.32
    - psutil >=6.1.1,<7
    - sbt == 1.9.6
    - dtc >=1.7.2,<2
    - gcc_linux-64 >=14.2.0,<15
    - gxx_linux-64 >=14.2.0,<15
    - gcc >=14.2.0,<14.3
    - gxx >=14.2.0,<14.3
    - binutils >=2.43,<3
    - boost >= 1.85.0,<2
    - boost-cpp >= 1.85.0,<2
    - tabulate >=0.9.0,<0.10
    - setuptools >=75.8.0,<76

build:
  script:
    - build.sh
