# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

name: build-conda
on:
  workflow_dispatch:
jobs:
  build-conda:
    build:
    runs-on: ubuntu-latest
    needs: build-docker
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build conda package
        uses: prefix-dev/rattler-build-action@v0.2.23
        with:
          recipe-path: util/conda/recipe.yaml

