# Copyright 2020 ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

# Run functional regression checks
name: ci
on: [push, pull_request]
jobs:

  ########
  # Docs #
  ########

  docs:
    name: Build documentation
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/snitch_cluster:ipc-verification
    steps:
      - uses: actions/checkout@v2
      - name: Build docs
        run: mkdocs build

  ##############################################
  # Simulate SW on Snitch Cluster w/ Verilator #
  ##############################################

  sw-snitch-cluster-vlt:
    name: Simulate SW on Snitch Cluster w/ Verilator
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/snitch_cluster:ipc-verification
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build Software
        run: |
          make -C target/snitch_cluster sw
      - name: Build Hardware
        run: |
          make -C target/snitch_cluster bin/snitch_cluster.vlt
      - name: Run Tests
        working-directory: target/snitch_cluster
        run: |-
          ./sw/tests/run.py sw/tests/run.yaml --simulator verilator
          ./sw/apps/run.py sw/apps/run.yaml --simulator verilator

  sw-snax-cluster-vlt:
    name: Simulate SW on SNAX Cluster w/ Verilator
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/snitch_cluster:ipc-verification
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Load Architecture
        # The makefile looks for lru.hjson
        # Need to copy-paste default or snax config to lru.hjson
        run: |
          cp target/snitch_cluster/cfg/snax.hjson \
          target/snitch_cluster/cfg/lru.hjson
      - name: Build Hardware
        run: |
          make -C target/snitch_cluster bin/snitch_cluster.vlt
      - name: Build Software
        run: |
          make -C target/snitch_cluster sw
      - name: Run Tests
        working-directory: target/snitch_cluster
        run: |-
          ./sw/tests/run.py sw/tests/snax-run.yaml --simulator verilator
          ./sw/apps/run.py sw/apps/run.yaml --simulator verilator

  ############################################
  # Build SW on Snitch Cluster w/ Banshee #
  ############################################

  sw-snitch-cluster-banshee:
    name: Simulate SW on Snitch Cluster w/ Banshee
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/pulp-platform/snitch_cluster:ipc-verification
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Build Software
        run: |
          make -C target/snitch_cluster SELECT_RUNTIME=banshee sw
      - name: Run Tests
        env:
          SNITCH_LOG: info
        working-directory: target/snitch_cluster
        run: |-
          ./sw/tests/run.py sw/tests/run.yaml --simulator banshee
          ./sw/apps/run.py sw/apps/run.yaml --simulator banshee
