# Copyright 2023 KU Leuven.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0
#
# Xiaoling Yi <xiaoling.yi@esat.kuleuven.be>

# Run Scala Unit Test
name: Run Scala Unit Test
on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  run:
    name: Build and Test
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/kuleuven-micas/snax:main
    steps:
      - uses: actions/checkout@v2
      - name: Run the unit tests
        working-directory: hw/chisel
        run: |
          mill Snax.test
      - name: Test xdma streamer
        working-directory: hw/chisel
        run: |-
          sbt "testOnly snax.xdma.xdmaStreamer.*"
      - name: Test xdma DataPath and Controller
        working-directory: hw/chisel
        run: |-
          sbt "testOnly snax.xdma.xdmaFrontend.*"
      - name: Test xdma Extension Framework + MaxPool
        working-directory: hw/chisel
        run: |-
          sbt "testOnly snax.xdma.xdmaExtension.*"
      - name: Test xdma Top Module
        working-directory: hw/chisel
        run: |-
          sbt "testOnly snax.xdma.xdmaTop.*"
